# EXAMPLE
# In production, this file should be controlled per machine via shared_configs to accomplish task segregation.
#
# These are queue names (like would be passed as QUEUES=... rake resque:work)
# and the count of workers that should be spun up to service them.
checksum_validation: 3
zip_endpoint_events: 4
"s3_us_east_1_delivery,s3_us_west_2_delivery": 6
"zipmaker,zips_made": 4
